name: Push to master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20 

      - uses: actions/setup-node@v1
        with:
          node-version: '13'

      - run: yarn install --frozen-lockfile
      - run: yarn lerna bootstrap

      - run: >-
          git config --global user.email "kristiyan.serafimov@gmail.com";
          git config --global user.name "krisbot";

      - run: yarn lerna version --conventional-commits --conventional-graduate -y