name: Push to master

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '13'

      - run: yarn install --frozen-lockfile
      - run: yarn lerna bootstrap